<?php
declare(strict_types=1);

/**
 * アセスメント設問定義
 *
 * question_type:
 *   'likert'         : 1=全くそう思わない … 5=とてもそう思う（高得点 = 良い）
 *   'reverse_likert' : 逆転項目（1=とてもそう思う → スコアは5点換算）
 *   'scenario'       : 選択肢に個別スコアを持つシナリオ型
 *
 * is_flag_trigger: true かつ score <= flag_threshold で警告フラグ発動
 */

define('ASSESSMENT_QUESTIONS', [

    // ════════════════════════════════════════════════════════
    // 恋愛偏差値（love_score）
    // ════════════════════════════════════════════════════════

    // ──────────── A. 感情の成熟度（weight: 25）────────────
    ['type'=>'love_score','cat'=>'A','sub'=>'A-1','order'=>1,
     'q_type'=>'scenario',
     'text'=>'パートナーが約束した時間に30分以上遅刻し、連絡もなかった。どう対応しますか？',
     'options'=>[
         ['label'=>'その場で強く責める',             'score'=>1],
         ['label'=>'不満を黙って溜め込む',            'score'=>2],
         ['label'=>'何も言わずにやり過ごす',          'score'=>2],
         ['label'=>'後で冷静に「心配したよ」と伝える','score'=>4],
         ['label'=>'具体的な気持ちを穏やかに言語化する','score'=>5],
     ]],
    ['type'=>'love_score','cat'=>'A','sub'=>'A-2','order'=>2,
     'q_type'=>'reverse_likert',
     'text'=>'仕事でストレスが溜まったとき、パートナーへの態度が冷たくなることがある'],
    ['type'=>'love_score','cat'=>'A','sub'=>'A-3','order'=>3,
     'q_type'=>'likert',
     'text'=>'怒りを感じたとき、まず自分の中で感情を整理してから相手に伝えることができる'],
    ['type'=>'love_score','cat'=>'A','sub'=>'A-4','order'=>4,
     'q_type'=>'reverse_likert',
     'text'=>'親しくなると言葉遣いや態度が最初より雑になると、周りから言われたことがある'],
    ['type'=>'love_score','cat'=>'A','sub'=>'A-5','order'=>5,
     'q_type'=>'reverse_likert',
     'text'=>'不満を我慢し続け、ある日突然感情が爆発してしまった経験がある'],
    ['type'=>'love_score','cat'=>'A','sub'=>'A-6','order'=>6,
     'q_type'=>'likert',
     'text'=>'相手への不満は「私は〜と感じた」という形で、批判せずに伝えることができる'],

    // ──────────── B. 自立性と相互尊重（weight: 25）────────────
    ['type'=>'love_score','cat'=>'B','sub'=>'B-1','order'=>7,
     'q_type'=>'scenario',
     'text'=>'デートの費用についてどう考えますか？',
     'options'=>[
         ['label'=>'男性が全額払うのが当然だと思う',          'score'=>1],
         ['label'=>'多く払うことで相手の気持ちを動かせると思う','score'=>2],
         ['label'=>'状況に応じて払う場合もあるが、割り勘が基本','score'=>3],
         ['label'=>'お互いの状況を話し合って決めるべき',       'score'=>5],
         ['label'=>'出す金額より一緒に楽しむことが大事',       'score'=>4],
     ]],
    ['type'=>'love_score','cat'=>'B','sub'=>'B-2','order'=>8,
     'q_type'=>'reverse_likert',
     'text'=>'パートナーからの連絡が少ないと、不安になって何度もメッセージを送ってしまう'],
    ['type'=>'love_score','cat'=>'B','sub'=>'B-3','order'=>9,
     'q_type'=>'reverse_likert',
     'text'=>'相手に認めてもらえないと感じると、気持ちが大きく落ち込んでしまう'],
    ['type'=>'love_score','cat'=>'B','sub'=>'B-4','order'=>10,
     'q_type'=>'likert',
     'text'=>'パートナーが自分と異なる意見を持っていても、その意見を尊重できる'],
    ['type'=>'love_score','cat'=>'B','sub'=>'B-5','order'=>11,
     'q_type'=>'reverse_likert',
     'text'=>'高価なプレゼントや食事で、相手の気持ちを自分に向けようとしたことがある'],
    ['type'=>'love_score','cat'=>'B','sub'=>'B-6','order'=>12,
     'q_type'=>'reverse_likert',
     'text'=>'パートナーには自分のために動いてくれることを期待してしまう'],

    // ──────────── C. 未来志向性・外見の自己受容（weight: 20）────────────
    ['type'=>'love_score','cat'=>'C','sub'=>'C-1','order'=>13,
     'q_type'=>'scenario',
     'text'=>'元交際相手の話題になったとき、どんな気持ちになりますか？',
     'options'=>[
         ['label'=>'今でも強い怒りや悲しみがよみがえる',                  'score'=>1],
         ['label'=>'モヤモヤするが、話題にするのは嫌だ',                  'score'=>2],
         ['label'=>'少し引きずっているが、日常には影響しない',            'score'=>3],
         ['label'=>'過去のことと割り切れている',                         'score'=>4],
         ['label'=>'今の自分を作ってくれた経験として受け入れている',      'score'=>5],
     ]],
    ['type'=>'love_score','cat'=>'C','sub'=>'C-2','order'=>14,
     'q_type'=>'likert',
     'text'=>'自分の外見（顔・体型）をおおむね受け入れ、肯定的に捉えることができる'],
    ['type'=>'love_score','cat'=>'C','sub'=>'C-3','order'=>15,
     'q_type'=>'likert',
     'text'=>'外見的に「似ている」カップルが長続きしやすいという考え方に共感できる'],
    ['type'=>'love_score','cat'=>'C','sub'=>'C-4','order'=>16,
     'q_type'=>'likert',
     'text'=>'過去の失恋から学び、現在の恋愛観をアップデートできていると思う'],
    ['type'=>'love_score','cat'=>'C','sub'=>'C-5','order'=>17,
     'q_type'=>'reverse_likert',
     'text'=>'交際相手の外見は、モデルや芸能人レベルの容姿であるべきだと思う'],

    // ──────────── K. 自己認識の客観性（weight: 15）★要注意フラグ ────────────
    ['type'=>'love_score','cat'=>'K','sub'=>'K-1','order'=>18,
     'q_type'=>'scenario',
     'text'=>'過去の恋愛がうまくいかなかった原因は何だったと思いますか？',
     'options'=>[
         ['label'=>'相手に問題があったと思う',                           'score'=>1],
         ['label'=>'タイミングや環境の問題だった',                       'score'=>2],
         ['label'=>'お互いに合わなかった部分があった',                   'score'=>3],
         ['label'=>'自分にも改善できた点があったと思う',                 'score'=>4],
         ['label'=>'自分の言動パターンを振り返り、具体的に認識できている','score'=>5],
     ],
     'is_flag'=>true,'flag_threshold'=>2],
    ['type'=>'love_score','cat'=>'K','sub'=>'K-2','order'=>19,
     'q_type'=>'likert',
     'text'=>'自分の恋愛における癖や繰り返しパターンを、言葉で説明できる',
     'is_flag'=>true,'flag_threshold'=>2],
    ['type'=>'love_score','cat'=>'K','sub'=>'K-3','order'=>20,
     'q_type'=>'likert',
     'text'=>'自分の言動が相手を傷つけていたと、後から気づいた経験がある（気づけた）'],
    ['type'=>'love_score','cat'=>'K','sub'=>'K-4','order'=>21,
     'q_type'=>'scenario',
     'text'=>'友人から「それはあなたにも原因があるのでは」と言われたとき、どう感じますか？',
     'options'=>[
         ['label'=>'腹が立ち、反論したくなる',                           'score'=>1],
         ['label'=>'不快だが、その場では黙って聞く',                     'score'=>2],
         ['label'=>'少し傷つくが、考えるきっかけにする',                 'score'=>3],
         ['label'=>'素直に受け止め、振り返ろうとする',                   'score'=>4],
         ['label'=>'貴重なフィードバックとして感謝する',                 'score'=>5],
     ],
     'is_flag'=>true,'flag_threshold'=>2],
    ['type'=>'love_score','cat'=>'K','sub'=>'K-5','order'=>22,
     'q_type'=>'likert',
     'text'=>'自分の感情の傾向（怒りやすい、寂しがりやすい等）を自覚し、対処できている',
     'is_flag'=>true,'flag_threshold'=>2],

    // ──────────── D. プライドの健全性（weight: 15）────────────
    ['type'=>'love_score','cat'=>'D','sub'=>'D-1','order'=>23,
     'q_type'=>'scenario',
     'text'=>'交際相手が自分より高い年収・社会的評価を得ているとき、どう感じますか？',
     'options'=>[
         ['label'=>'劣等感を感じ、不安になる',                           'score'=>1],
         ['label'=>'複雑な気持ちになり、意識してしまう',                 'score'=>2],
         ['label'=>'特に気にしない',                                     'score'=>3],
         ['label'=>'頼もしく感じ、自分も頑張ろうと思う',                 'score'=>4],
         ['label'=>'心から誇らしく、一緒にいることが嬉しい',             'score'=>5],
     ]],
    ['type'=>'love_score','cat'=>'D','sub'=>'D-2','order'=>24,
     'q_type'=>'likert',
     'text'=>'自分が間違えたと分かったとき、素直に謝ることができる'],
    ['type'=>'love_score','cat'=>'D','sub'=>'D-3','order'=>25,
     'q_type'=>'reverse_likert',
     'text'=>'パートナーの外見やスペックを、友人に自慢したいという気持ちがある'],
    ['type'=>'love_score','cat'=>'D','sub'=>'D-4','order'=>26,
     'q_type'=>'likert',
     'text'=>'相手が自分より優れた成果を出したとき、心から喜ぶことができる'],
    ['type'=>'love_score','cat'=>'D','sub'=>'D-5','order'=>27,
     'q_type'=>'scenario',
     'text'=>'議論で自分の誤りが明らかになってきたとき、どうしますか？',
     'options'=>[
         ['label'=>'話題を変えるか、黙り込む',                           'score'=>1],
         ['label'=>'言い訳を探してしまう',                               'score'=>2],
         ['label'=>'渋々認めるが、後味が悪い',                           'score'=>3],
         ['label'=>'素直に「そうだね」と認められる',                     'score'=>4],
         ['label'=>'間違いを認め、感謝を伝えられる',                     'score'=>5],
     ]],

    // ──────────── E. 継続関係への意志（weight: 10）────────────
    ['type'=>'love_score','cat'=>'E','sub'=>'E-1','order'=>28,
     'q_type'=>'scenario',
     'text'=>'関係がうまくいかなくなったとき、最初にとる行動は？',
     'options'=>[
         ['label'=>'自然消滅を待つ、または距離を置く',                   'score'=>1],
         ['label'=>'相手のせいにして不満を伝える',                       'score'=>2],
         ['label'=>'一時的に冷静になってから考える',                     'score'=>3],
         ['label'=>'二人で話し合いの場を設ける',                         'score'=>4],
         ['label'=>'問題を整理し、建設的に対話する',                     'score'=>5],
     ]],
    ['type'=>'love_score','cat'=>'E','sub'=>'E-2','order'=>29,
     'q_type'=>'likert',
     'text'=>'パートナーが自己成長のためにお金や時間を使うことを、心から応援できる'],
    ['type'=>'love_score','cat'=>'E','sub'=>'E-3','order'=>30,
     'q_type'=>'likert',
     'text'=>'困難なときに逃げず、パートナーと一緒に乗り越えた経験（または意志）がある'],
    ['type'=>'love_score','cat'=>'E','sub'=>'E-4','order'=>31,
     'q_type'=>'likert',
     'text'=>'短期的な楽しさより、長期的な関係の質を重視したいと思っている'],

    // ──────────── L. 関係修復・場の調整力（weight: 10）────────────
    ['type'=>'love_score','cat'=>'L','sub'=>'L-1','order'=>32,
     'q_type'=>'scenario',
     'text'=>'二人の間に気まずい空気が流れたとき、どう対処しますか？',
     'options'=>[
         ['label'=>'沈黙が続いてもそのまま放置する',                     'score'=>1],
         ['label'=>'相手が動くまで待つ',                                 'score'=>2],
         ['label'=>'話題を変えて自然に流そうとする',                     'score'=>3],
         ['label'=>'ユーモアや軽い言葉で場を和ませる',                   'score'=>4],
         ['label'=>'率先して「さっきの話、ちゃんとしよう」と切り出せる', 'score'=>5],
     ]],
    ['type'=>'love_score','cat'=>'L','sub'=>'L-2','order'=>33,
     'q_type'=>'reverse_likert',
     'text'=>'パートナーの過去の失言や失敗を、何年も経ってから蒸し返すことがある'],
    ['type'=>'love_score','cat'=>'L','sub'=>'L-3','order'=>34,
     'q_type'=>'likert',
     'text'=>'喧嘩や衝突の後、雰囲気を和ませるために自分から動くことができる'],
    ['type'=>'love_score','cat'=>'L','sub'=>'L-4','order'=>35,
     'q_type'=>'likert',
     'text'=>'相手の些細なミスや失敗を、笑いに変えて一緒に楽しめることがある'],

    // ──────────── M. 問題解決とリーダーシップ（weight: 10）────────────
    ['type'=>'love_score','cat'=>'M','sub'=>'M-1','order'=>36,
     'q_type'=>'scenario',
     'text'=>'二人の間に問題が起きたとき、どう捉えますか？',
     'options'=>[
         ['label'=>'どちらかが悪いと思う（勝ち負け）',                   'score'=>1],
         ['label'=>'相手に変わってほしいと思う',                         'score'=>2],
         ['label'=>'二人の問題として考えようとする',                     'score'=>3],
         ['label'=>'「私たち vs 問題」として協力して解決しようとする',   'score'=>5],
         ['label'=>'問題を整理し、互いの役割分担を話し合う',             'score'=>4],
     ]],
    ['type'=>'love_score','cat'=>'M','sub'=>'M-2','order'=>37,
     'q_type'=>'likert',
     'text'=>'デートや日常の意思決定を、相手の意見も聞きながら主体的に進められる'],
    ['type'=>'love_score','cat'=>'M','sub'=>'M-3','order'=>38,
     'q_type'=>'likert',
     'text'=>'パートナーが落ち込んでいるとき、解決策を押しつけず、まず寄り添える'],
    ['type'=>'love_score','cat'=>'M','sub'=>'M-4','order'=>39,
     'q_type'=>'likert',
     'text'=>'二人のためになることを、率先して考え行動できる'],

    // ──────────── N. 誠実さ・言動の一貫性（weight: 10）★要注意フラグ ────────────
    ['type'=>'love_score','cat'=>'N','sub'=>'N-1','order'=>40,
     'q_type'=>'scenario',
     'text'=>'このアプリを使う目的（真剣か、そうでないか）を相手に正直に伝えることについて',
     'options'=>[
         ['label'=>'目的は状況次第で変えていい',                         'score'=>1],
         ['label'=>'相手を傷つけないため、曖昧にしておく方がいい',       'score'=>2],
         ['label'=>'聞かれたら正直に答える',                             'score'=>3],
         ['label'=>'早い段階で自分の意図を伝えるべきだと思う',           'score'=>4],
         ['label'=>'相手の時間と感情を尊重するために必ず伝える',         'score'=>5],
     ],
     'is_flag'=>true,'flag_threshold'=>2],
    ['type'=>'love_score','cat'=>'N','sub'=>'N-2','order'=>41,
     'q_type'=>'likert',
     'text'=>'プロフィールや自己紹介の内容と、実際の自分の生活・性格は一致している'],
    ['type'=>'love_score','cat'=>'N','sub'=>'N-3','order'=>42,
     'q_type'=>'reverse_likert',
     'text'=>'複数の人と同時に関係を進めることは、相手が知らなければ問題ないと思う'],
    ['type'=>'love_score','cat'=>'N','sub'=>'N-4','order'=>43,
     'q_type'=>'likert',
     'text'=>'約束を破ってしまったとき、言い訳をせず誠実に謝罪することができる'],
    ['type'=>'love_score','cat'=>'N','sub'=>'N-5','order'=>44,
     'q_type'=>'scenario',
     'text'=>'相手を傷つけないために、事実と異なることを伝えることについて',
     'options'=>[
         ['label'=>'相手のためなら嘘も必要だと思う',                     'score'=>1],
         ['label'=>'状況によっては仕方ない',                             'score'=>2],
         ['label'=>'できれば避けたいが、場合によっては仕方ない',         'score'=>3],
         ['label'=>'傷つけたくないなら、伝え方を工夫すべき',             'score'=>4],
         ['label'=>'どんな状況でも誠実であることが相手への敬意',         'score'=>5],
     ],
     'is_flag'=>true,'flag_threshold'=>2],

    // ════════════════════════════════════════════════════════
    // 可愛さ指数（cute_score）
    // ════════════════════════════════════════════════════════

    // ──────────── F. 感謝と承認の表現力（weight: 20）────────────
    ['type'=>'cute_score','cat'=>'F','sub'=>'F-1','order'=>1,
     'q_type'=>'scenario',
     'text'=>'パートナーが時間をかけて料理や計画を準備してくれたとき、どう反応しますか？',
     'options'=>[
         ['label'=>'特に何も言わない（当たり前と思っている）','score'=>1],
         ['label'=>'「ありがとう」と一言だけ伝える',         'score'=>2],
         ['label'=>'感謝を伝え、「美味しい」等の感想を言う', 'score'=>3],
         ['label'=>'具体的に「〇〇が特に嬉しかった」と伝える','score'=>4],
         ['label'=>'準備の過程も含めて感謝し、喜びを全力で表現する','score'=>5],
     ]],
    ['type'=>'cute_score','cat'=>'F','sub'=>'F-2','order'=>2,
     'q_type'=>'likert',
     'text'=>'「ありがとう」を、何が嬉しかったかを具体的にして伝えることができる'],
    ['type'=>'cute_score','cat'=>'F','sub'=>'F-3','order'=>3,
     'q_type'=>'likert',
     'text'=>'相手の小さな気遣いや配慮に気づき、それを相手に伝えることがある'],
    ['type'=>'cute_score','cat'=>'F','sub'=>'F-4','order'=>4,
     'q_type'=>'likert',
     'text'=>'相手の良いところや素敵だと思った点を、本人に直接伝えることができる'],
    ['type'=>'cute_score','cat'=>'F','sub'=>'F-5','order'=>5,
     'q_type'=>'likert',
     'text'=>'相手が自分の人生に存在してくれること自体に、感謝を感じることがある'],

    // ──────────── I. 心理的安全性の提供（weight: 20）────────────
    ['type'=>'cute_score','cat'=>'I_cute','sub'=>'I-1','order'=>6,
     'q_type'=>'scenario',
     'text'=>'パートナーが「仕事がつらい、もうやめたい」と弱音を吐いてきたとき、どうしますか？',
     'options'=>[
         ['label'=>'「そんなこと言っても仕方ない」と現実を伝える',       'score'=>1],
         ['label'=>'すぐ解決策を提案する',                               'score'=>2],
         ['label'=>'「大変だったね」と共感する',                         'score'=>3],
         ['label'=>'まず「どんな気持ちか」を聞いてから一緒に考える',     'score'=>4],
         ['label'=>'ただそばにいて、話を最後まで聞いてから気持ちを受け止める','score'=>5],
     ]],
    ['type'=>'cute_score','cat'=>'I_cute','sub'=>'I-2','order'=>7,
     'q_type'=>'likert',
     'text'=>'相手から打ち明けられた秘密や悩みを、他の人に話さないでいられる'],
    ['type'=>'cute_score','cat'=>'I_cute','sub'=>'I-3','order'=>8,
     'q_type'=>'likert',
     'text'=>'相手が話しているとき、スマホを置いて目を見て聞くことができる'],
    ['type'=>'cute_score','cat'=>'I_cute','sub'=>'I-4','order'=>9,
     'q_type'=>'likert',
     'text'=>'自分が元気でないときでも、相手の気持ちや状態に気を配ることができる'],
    ['type'=>'cute_score','cat'=>'I_cute','sub'=>'I-5','order'=>10,
     'q_type'=>'likert',
     'text'=>'相手が「こんなこと言っていいかな」と迷わず話せる雰囲気を作れていると思う'],

    // ──────────── G. 素直さと自己開示（weight: 15）────────────
    ['type'=>'cute_score','cat'=>'G','sub'=>'G-1','order'=>11,
     'q_type'=>'likert',
     'text'=>'自分の弱さや失敗談を、親しいパートナーに自然に打ち明けることができる'],
    ['type'=>'cute_score','cat'=>'G','sub'=>'G-2','order'=>12,
     'q_type'=>'reverse_likert',
     'text'=>'意地を張ってしまい、素直になれなかったと後悔した経験が度々ある'],
    ['type'=>'cute_score','cat'=>'G','sub'=>'G-3','order'=>13,
     'q_type'=>'likert',
     'text'=>'困ったときや助けが必要なとき、「助けて」と言葉にして頼ることができる'],
    ['type'=>'cute_score','cat'=>'G','sub'=>'G-4','order'=>14,
     'q_type'=>'likert',
     'text'=>'自分の不安や心配事を、パートナーに素直に言葉で伝えることができる'],

    // ──────────── H. ユーモアと愛嬌（weight: 15）────────────
    ['type'=>'cute_score','cat'=>'H','sub'=>'H-1','order'=>15,
     'q_type'=>'scenario',
     'text'=>'二人の間に気まずい沈黙が続いたとき、どうしますか？',
     'options'=>[
         ['label'=>'そのまま沈黙を続ける',                               'score'=>1],
         ['label'=>'スマホを見て誤魔化す',                               'score'=>2],
         ['label'=>'天気など無難な話題を出す',                           'score'=>3],
         ['label'=>'「沈黙もいいよね」と笑いながら言える',               'score'=>4],
         ['label'=>'ユーモアや遊び心で自然に場の空気を変えられる',       'score'=>5],
     ]],
    ['type'=>'cute_score','cat'=>'H','sub'=>'H-2','order'=>16,
     'q_type'=>'likert',
     'text'=>'自分の失敗や恥ずかしいエピソードを、笑い話として話せることがある'],
    ['type'=>'cute_score','cat'=>'H','sub'=>'H-3','order'=>17,
     'q_type'=>'likert',
     'text'=>'場の雰囲気を明るくしたり、笑いを生み出す役割を担えることがある'],
    ['type'=>'cute_score','cat'=>'H','sub'=>'H-4','order'=>18,
     'q_type'=>'likert',
     'text'=>'相手を笑わせたい、喜ばせたいという気持ちが自然と湧いてくる'],

    // ──────────── J. 本物の優しさ（weight: 10）────────────
    ['type'=>'cute_score','cat'=>'J','sub'=>'J-1','order'=>19,
     'q_type'=>'scenario',
     'text'=>'パートナーから無理な要求や理不尽なお願いをされたとき、どうしますか？',
     'options'=>[
         ['label'=>'嫌でも全部受け入れてしまう',                         'score'=>1],
         ['label'=>'不満を抱えながらも従う',                             'score'=>2],
         ['label'=>'「今回は難しい」と断れることもある',                 'score'=>3],
         ['label'=>'相手の気持ちを尊重しながら、理由を添えて断れる',     'score'=>4],
         ['label'=>'「No」を伝えることも愛情だと思い、誠実に伝えられる', 'score'=>5],
     ]],
    ['type'=>'cute_score','cat'=>'J','sub'=>'J-2','order'=>20,
     'q_type'=>'likert',
     'text'=>'相手のためになると思えば、相手が嫌がることでも誠実に伝えることができる'],
    ['type'=>'cute_score','cat'=>'J','sub'=>'J-3','order'=>21,
     'q_type'=>'likert',
     'text'=>'相手が間違っていると思ったとき、傷つけない言い方を工夫して伝えられる'],
    ['type'=>'cute_score','cat'=>'J','sub'=>'J-4','order'=>22,
     'q_type'=>'scenario',
     'text'=>'「優しさ」とはどういうことだと思いますか？',
     'options'=>[
         ['label'=>'相手の言うことをすべて受け入れること',               'score'=>1],
         ['label'=>'相手を傷つけないこと',                               'score'=>2],
         ['label'=>'相手が喜ぶことをしてあげること',                     'score'=>3],
         ['label'=>'相手の気持ちを理解しようとすること',                 'score'=>4],
         ['label'=>'相手の長期的な幸福を願い、時に厳しいことも伝えること','score'=>5],
     ]],

    // ──────────── PQ. 相手への好奇心（weight: 10）────────────
    ['type'=>'cute_score','cat'=>'PQ','sub'=>'PQ-1','order'=>23,
     'q_type'=>'likert',
     'text'=>'前回の会話で相手が話していたこと（悩みや出来事）を、次に会ったとき覚えている'],
    ['type'=>'cute_score','cat'=>'PQ','sub'=>'PQ-2','order'=>24,
     'q_type'=>'likert',
     'text'=>'付き合いが長くなっても、相手のことをもっと知りたいという気持ちが続いている'],
    ['type'=>'cute_score','cat'=>'PQ','sub'=>'PQ-3','order'=>25,
     'q_type'=>'likert',
     'text'=>'相手が新しく始めた趣味や関心事に、興味を持って質問することができる'],
    ['type'=>'cute_score','cat'=>'PQ','sub'=>'PQ-4','order'=>26,
     'q_type'=>'likert',
     'text'=>'相手の内面（価値観・考え方・夢）への関心が、外見への関心と同じかそれ以上ある'],

    // ──────────── OR. 自分軸の確立（weight: 10）────────────
    ['type'=>'cute_score','cat'=>'OR','sub'=>'OR-1','order'=>27,
     'q_type'=>'likert',
     'text'=>'パートナーがいなくても、自分の日常を充実させることができる'],
    ['type'=>'cute_score','cat'=>'OR','sub'=>'OR-2','order'=>28,
     'q_type'=>'likert',
     'text'=>'自分の価値観や大切にしていることを、言葉にして説明できる'],
    ['type'=>'cute_score','cat'=>'OR','sub'=>'OR-3','order'=>29,
     'q_type'=>'likert',
     'text'=>'恋愛以外にも、熱中できることや目標がある'],
    ['type'=>'cute_score','cat'=>'OR','sub'=>'OR-4','order'=>30,
     'q_type'=>'reverse_likert',
     'text'=>'相手に「幸せにしてもらいたい」という気持ちが強くある'],
]);

/**
 * アセスメントタイプ別カテゴリ重み（正規化前の生値）
 * 合計が100にならない場合は ScoringEngine 内で正規化する
 */
define('CATEGORY_WEIGHTS', [
    'love_score' => [
        'A'=>25,'B'=>25,'C'=>20,'K'=>15,'D'=>15,
        'E'=>10,'L'=>10,'M'=>10,'N'=>10,
    ],
    'cute_score' => [
        'F'=>20,'I_cute'=>20,'G'=>15,'H'=>15,
        'J'=>10,'PQ'=>10,'OR'=>10,
    ],
]);

define('CATEGORY_LABELS', [
    'A'      => '感情の成熟度',
    'B'      => '自立性と相互尊重',
    'C'      => '未来志向性・外見の自己受容',
    'K'      => '自己認識の客観性',
    'D'      => 'プライドの健全性',
    'E'      => '継続関係への意志',
    'L'      => '関係修復・場の調整力',
    'M'      => '問題解決とリーダーシップ',
    'N'      => '誠実さ・言動の一貫性',
    'F'      => '感謝と承認の表現力',
    'I_cute' => '心理的安全性の提供',
    'G'      => '素直さと自己開示',
    'H'      => 'ユーモアと愛嬌',
    'J'      => '本物の優しさ',
    'PQ'     => '相手への好奇心',
    'OR'     => '自分軸の確立',
]);
